ports:
  - port: 3000
    onOpen: open-preview


# .gitpod.yml

# Use the Node.js base image
image:
  file: .gitpod.Dockerfile

# List of initial commands to run during workspace initialization
# Install dependencies and start Playwright tests
tasks:
#  - init: npm install
  - command: npx playwright test
